{ pkgs }:

[
  (pkgs.callPackage ./nix-Hypridle.nix { })
  (pkgs.callPackage ./nix-Hyprsunset.nix { })
  (pkgs.callPackage ./nix-KeyBinds.nix { })
  (pkgs.callPackage ./nix-KeybindsLayoutInit.nix { })
  (pkgs.callPackage ./nix-KeyHints.nix { })
  (pkgs.callPackage ./nix-KillActiveProcess.nix { })
  (pkgs.callPackage ./nix-Kitty_themes.nix { })
  (pkgs.callPackage ./nix-Kool_Quick_Settings.nix { })
  (pkgs.callPackage ./nix-KooLsDotsUpdate.nix { })
  (pkgs.callPackage ./nix-LockScreen.nix { })
  (pkgs.callPackage ./nix-MediaCtrl.nix { })
  (pkgs.callPackage ./nix-MonitorProfiles.nix { })
  (pkgs.callPackage ./nix-OverviewToggle.nix { })
  (pkgs.callPackage ./nix-Polkit-NixOS.nix { })
  (pkgs.callPackage ./nix-Polkit.nix { })
  (pkgs.callPackage ./nix-PortalHyprland.nix { })
  (pkgs.callPackage ./nix-Refresh.nix { })
  (pkgs.callPackage ./nix-RefreshNoWaybar.nix { })
  #(pkgs.callPackage ./nix-RofiEmoji.nix { })
  (pkgs.callPackage ./nix-RofiSearch.nix { })
  (pkgs.callPackage ./nix-RofiThemeSelector-modified.nix { })
  (pkgs.callPackage ./nix-RofiThemeSelector.nix { })
  (pkgs.callPackage ./nix-ScreenShot.nix { })
  (pkgs.callPackage ./nix-sddm_wallpaper.nix { })
  (pkgs.callPackage ./nix-Sounds.nix { })
  (pkgs.callPackage ./nix-SwitchKeyboardLayout.nix { })
  (pkgs.callPackage ./nix-Tak0-Autodispatch.nix { })
  (pkgs.callPackage ./nix-Tak0-Per-Window-Switch.nix { })
  (pkgs.callPackage ./nix-TouchPad.nix { })
  (pkgs.callPackage ./nix-UptimeNixOS.nix { })
  (pkgs.callPackage ./nix-UserConfigsSwitcher.nix { })
  (pkgs.callPackage ./nix-Volume.nix { })
  (pkgs.callPackage ./nix-WallustSwww.nix { })
  (pkgs.callPackage ./nix-WaybarCava.nix { })
  (pkgs.callPackage ./nix-WaybarLayout.nix { })
  (pkgs.callPackage ./nix-WaybarScripts.nix { })
  (pkgs.callPackage ./nix-WaybarStyles.nix { })
  (pkgs.callPackage ./nix-Wlogout.nix { })
]